### ISSUE TITLE
std

### ISSUE THREAD

**Issue by shreyaslad** [KingPixil/arc#1]
Adding -std=gnu11 to your CFLAGS (or gcc if since you dont use a makefile) will give you access to stdint.h, stdbool.h, stddef.h, stdarg.h, atomic.h, etc...

**Comment by kbrsh** [comment]
Yup, I had plans to use the standard library as development continued, but didn't use it at the start to prevent it from interfering with any kernel code (hence the `-ffreestanding`). Development didn't ever continue though :(

**Comment by shreyaslad** [comment]
I'm pretty sure you have to compile it with ffreestanding to avoid gcc from trying to use the normal C standard library. That's sad tho :c

**Comment by kbrsh** [comment]
ffreestanding is to prevent it from making any assumptions based on stdlib function names. That way gcc won't assume access to certain stdlib functions or that the program will start at `main`.

Yeah, an OS is a huge undertaking, and I now have a completely different vision of what an ideal OS should be. I might write about it someday.
